# Generated by Django 4.1.3 on 2022-11-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('nat_code', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('decimal_age', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
